package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, 28 March 2012 16:50:28 o'clock CEST
*/

public interface ChatOperations 
{

  // Join
  String join (ChatApp.ChatCallback objref, String user);

  // Post
  void say (ChatApp.ChatCallback objref, String message, String user);

  // List
  String list ();

  // Leave
  void leave (String user);

  // Othello
  void othello (ChatApp.ChatCallback objref, String color, String user);

  // Move Othello
  void move (String move, String user);
} // interface ChatOperations
