module ChatApp {
  interface ChatCallback {
    void callback(in string message);
  };
  interface Chat {
    // Join
    string join(in ChatCallback objref, in string user);
    // Post
    void say(in ChatCallback objref, in string message, in string user);
    // List
    string list();
    // Leave
    // Quit
  };
};
